### ISSUE TITLE
Hi, where is the code

### ISSUE THREAD

**Issue by HappyWalkers** [AhmedMagdyHendawy/MOORE#1]

**Comment by Lan131** [comment]
Hello, I was also interested in this code. We wanted to cite it in our paper

**Comment by AhmedMagdyHendawy** [comment]
Hi all, 

Thank you for showing interest in our work!

I just pushed the codebase of our work. For now, I have only pushed the implementation for the minigrid benchmark. Later, I will add the metaworld too.

**Comment by Lan131** [comment]
Is there any way you can give us some instructions on what needs done to run metaworld? We have metaworld installed so if its something easy posting that would be great.

**Comment by AhmedMagdyHendawy** [comment]
Metaworld codebase has been added.

Cheers,
Ahmed
