### ISSUE TITLE
Metaworld experiments

### ISSUE THREAD

**Issue by reginald-mclean** [AhmedMagdyHendawy/MOORE#2]
Hello, 

Thanks for making your codebase public. Just wondering if the code for the Metaworld experiments will be added soon.

Thanks!

**Comment by AhmedMagdyHendawy** [comment]
Hi, 

I will work on cleaning up the Metaworld experiments over the weekend and push it soon. 

Best,
Ahmed

**Comment by AhmedMagdyHendawy** [comment]
I pushed the codebase of MOORE for Metaworld.
