### ISSUE TITLE
Using backbone RL algorithms other than PPO/SAC

### ISSUE THREAD

**Issue by xwen24** [AhmedMagdyHendawy/MOORE#3]
Hello!

Thanks so much for sharing the codes!

As a starter in multi-task RL, I have a question regarding MOORE: you mentioned that "MOORE is agnostic to the used RL algorithms" in your paper. If other RL algorithms (say DDPG) are adopted, can you please suggest how to modify MOORE to accommodate those algorithms?

Thanks in advance!

**Comment by AhmedMagdyHendawy** [comment]
Hi!

MOORE is an architecture-based approach. So, what you need to do for any RL algorithm is to change the architecture of the actor and the critic in the same way we change the ones for SAC and PPO. For instance, you can use a mixture of encoders and a task encoder to estimate the weight for combining the orthogonal representations. 

I hope that answer your question.

Best,
Ahmed

**Comment by xwen24** [comment]
Thanks so much for your help!
